
package ru.vetrf.api.schema.cdm.registry.enterprise.service.v2;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EnterpriseServiceBindingQSService", targetNamespace = "http://api.vetrf.ru/schema/cdm/registry/enterprise/service/v2", wsdlLocation = "http://api.vetrf.ru/schema/platform/services/2.1-RC-last/EnterpriseService_v2.1_production.wsdl")
public class EnterpriseServiceBindingQSService
    extends Service
{

    private final static URL ENTERPRISESERVICEBINDINGQSSERVICE_WSDL_LOCATION;
    private final static WebServiceException ENTERPRISESERVICEBINDINGQSSERVICE_EXCEPTION;
    private final static QName ENTERPRISESERVICEBINDINGQSSERVICE_QNAME = new QName("http://api.vetrf.ru/schema/cdm/registry/enterprise/service/v2", "EnterpriseServiceBindingQSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://api.vetrf.ru/schema/platform/services/2.1-RC-last/EnterpriseService_v2.1_production.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ENTERPRISESERVICEBINDINGQSSERVICE_WSDL_LOCATION = url;
        ENTERPRISESERVICEBINDINGQSSERVICE_EXCEPTION = e;
    }

    public EnterpriseServiceBindingQSService() {
        super(__getWsdlLocation(), ENTERPRISESERVICEBINDINGQSSERVICE_QNAME);
    }

    public EnterpriseServiceBindingQSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ENTERPRISESERVICEBINDINGQSSERVICE_QNAME, features);
    }

    public EnterpriseServiceBindingQSService(URL wsdlLocation) {
        super(wsdlLocation, ENTERPRISESERVICEBINDINGQSSERVICE_QNAME);
    }

    public EnterpriseServiceBindingQSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ENTERPRISESERVICEBINDINGQSSERVICE_QNAME, features);
    }

    public EnterpriseServiceBindingQSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EnterpriseServiceBindingQSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EnterpriseServicePortType
     */
    @WebEndpoint(name = "EnterpriseServiceBindingQSPort")
    public EnterpriseServicePortType getEnterpriseServiceBindingQSPort() {
        return super.getPort(new QName("http://api.vetrf.ru/schema/cdm/registry/enterprise/service/v2", "EnterpriseServiceBindingQSPort"), EnterpriseServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EnterpriseServicePortType
     */
    @WebEndpoint(name = "EnterpriseServiceBindingQSPort")
    public EnterpriseServicePortType getEnterpriseServiceBindingQSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://api.vetrf.ru/schema/cdm/registry/enterprise/service/v2", "EnterpriseServiceBindingQSPort"), EnterpriseServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ENTERPRISESERVICEBINDINGQSSERVICE_EXCEPTION!= null) {
            throw ENTERPRISESERVICEBINDINGQSSERVICE_EXCEPTION;
        }
        return ENTERPRISESERVICEBINDINGQSSERVICE_WSDL_LOCATION;
    }

}
