
package ru.vetrf.api.schema.cdm.registry.dictionary.service.v2;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DictionaryServiceBindingQSService", targetNamespace = "http://api.vetrf.ru/schema/cdm/registry/dictionary/service/v2", wsdlLocation = "http://api.vetrf.ru/schema/platform/services/2.1-RC-last/DictionaryService_v2.1_production.wsdl")
public class DictionaryServiceBindingQSService
    extends Service
{

    private final static URL DICTIONARYSERVICEBINDINGQSSERVICE_WSDL_LOCATION;
    private final static WebServiceException DICTIONARYSERVICEBINDINGQSSERVICE_EXCEPTION;
    private final static QName DICTIONARYSERVICEBINDINGQSSERVICE_QNAME = new QName("http://api.vetrf.ru/schema/cdm/registry/dictionary/service/v2", "DictionaryServiceBindingQSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://api.vetrf.ru/schema/platform/services/2.1-RC-last/DictionaryService_v2.1_production.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DICTIONARYSERVICEBINDINGQSSERVICE_WSDL_LOCATION = url;
        DICTIONARYSERVICEBINDINGQSSERVICE_EXCEPTION = e;
    }

    public DictionaryServiceBindingQSService() {
        super(__getWsdlLocation(), DICTIONARYSERVICEBINDINGQSSERVICE_QNAME);
    }

    public DictionaryServiceBindingQSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DICTIONARYSERVICEBINDINGQSSERVICE_QNAME, features);
    }

    public DictionaryServiceBindingQSService(URL wsdlLocation) {
        super(wsdlLocation, DICTIONARYSERVICEBINDINGQSSERVICE_QNAME);
    }

    public DictionaryServiceBindingQSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DICTIONARYSERVICEBINDINGQSSERVICE_QNAME, features);
    }

    public DictionaryServiceBindingQSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DictionaryServiceBindingQSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DictionaryServicePortType
     */
    @WebEndpoint(name = "DictionaryServiceBindingQSPort")
    public DictionaryServicePortType getDictionaryServiceBindingQSPort() {
        return super.getPort(new QName("http://api.vetrf.ru/schema/cdm/registry/dictionary/service/v2", "DictionaryServiceBindingQSPort"), DictionaryServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DictionaryServicePortType
     */
    @WebEndpoint(name = "DictionaryServiceBindingQSPort")
    public DictionaryServicePortType getDictionaryServiceBindingQSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://api.vetrf.ru/schema/cdm/registry/dictionary/service/v2", "DictionaryServiceBindingQSPort"), DictionaryServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DICTIONARYSERVICEBINDINGQSSERVICE_EXCEPTION!= null) {
            throw DICTIONARYSERVICEBINDINGQSSERVICE_EXCEPTION;
        }
        return DICTIONARYSERVICEBINDINGQSSERVICE_WSDL_LOCATION;
    }

}
