
package ru.vetrf.api.schema.cdm.application.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ApplicationManagementServiceBindingQSService", targetNamespace = "http://api.vetrf.ru/schema/cdm/application/service", wsdlLocation = "http://api.vetrf.ru/schema/platform/services/2.1-RC-last/ams-mercury-g2b.service_v2.1_production.wsdl")
public class ApplicationManagementServiceBindingQSService
    extends Service
{

    private final static URL APPLICATIONMANAGEMENTSERVICEBINDINGQSSERVICE_WSDL_LOCATION;
    private final static WebServiceException APPLICATIONMANAGEMENTSERVICEBINDINGQSSERVICE_EXCEPTION;
    private final static QName APPLICATIONMANAGEMENTSERVICEBINDINGQSSERVICE_QNAME = new QName("http://api.vetrf.ru/schema/cdm/application/service", "ApplicationManagementServiceBindingQSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://api.vetrf.ru/schema/platform/services/2.1-RC-last/ams-mercury-g2b.service_v2.1_production.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        APPLICATIONMANAGEMENTSERVICEBINDINGQSSERVICE_WSDL_LOCATION = url;
        APPLICATIONMANAGEMENTSERVICEBINDINGQSSERVICE_EXCEPTION = e;
    }

    public ApplicationManagementServiceBindingQSService() {
        super(__getWsdlLocation(), APPLICATIONMANAGEMENTSERVICEBINDINGQSSERVICE_QNAME);
    }

    public ApplicationManagementServiceBindingQSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), APPLICATIONMANAGEMENTSERVICEBINDINGQSSERVICE_QNAME, features);
    }

    public ApplicationManagementServiceBindingQSService(URL wsdlLocation) {
        super(wsdlLocation, APPLICATIONMANAGEMENTSERVICEBINDINGQSSERVICE_QNAME);
    }

    public ApplicationManagementServiceBindingQSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, APPLICATIONMANAGEMENTSERVICEBINDINGQSSERVICE_QNAME, features);
    }

    public ApplicationManagementServiceBindingQSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ApplicationManagementServiceBindingQSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ApplicationManagementServicePortType
     */
    @WebEndpoint(name = "ApplicationManagementServiceBindingQSPort")
    public ApplicationManagementServicePortType getApplicationManagementServiceBindingQSPort() {
        return super.getPort(new QName("http://api.vetrf.ru/schema/cdm/application/service", "ApplicationManagementServiceBindingQSPort"), ApplicationManagementServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ApplicationManagementServicePortType
     */
    @WebEndpoint(name = "ApplicationManagementServiceBindingQSPort")
    public ApplicationManagementServicePortType getApplicationManagementServiceBindingQSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://api.vetrf.ru/schema/cdm/application/service", "ApplicationManagementServiceBindingQSPort"), ApplicationManagementServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (APPLICATIONMANAGEMENTSERVICEBINDINGQSSERVICE_EXCEPTION!= null) {
            throw APPLICATIONMANAGEMENTSERVICEBINDINGQSSERVICE_EXCEPTION;
        }
        return APPLICATIONMANAGEMENTSERVICEBINDINGQSSERVICE_WSDL_LOCATION;
    }

}
