
package ru.vetrf.api.schema.cdm.application.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import ru.vetrf.api.schema.cdm.application.Application;
import ru.vetrf.api.schema.cdm.application.ws_definitions.ReceiveApplicationResultRequest;
import ru.vetrf.api.schema.cdm.application.ws_definitions.ReceiveApplicationResultResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ApplicationManagementServicePortType", targetNamespace = "http://api.vetrf.ru/schema/cdm/application/service")
@XmlSeeAlso({
    ru.vetrf.api.schema.cdm.mercury.vet_document.v2.ObjectFactory.class,
    ru.vetrf.api.schema.cdm.dictionary.v2.ObjectFactory.class,
    ru.vetrf.api.schema.cdm.application.ObjectFactory.class,
    ru.vetrf.api.schema.cdm.application.ws_definitions.ObjectFactory.class,
    ru.vetrf.api.schema.cdm.base.ObjectFactory.class,
    ru.vetrf.api.schema.cdm.base.ws_definitions.ObjectFactory.class,
    ru.vetrf.api.schema.cdm.mercury.g2b.applications.v2.ObjectFactory.class
})
public interface ApplicationManagementServicePortType {


    /**
     * 
     * @param apiKey
     * @param application
     * @throws AccessDeniedFault
     * @throws IncorrectRequestFault
     * @throws UnsupportedApplicationDataTypeFault
     * @throws InternalServiceFault
     * @throws UnknownServiceIdFault
     */
    @WebMethod(action = "submitApplicationRequest")
    @RequestWrapper(localName = "submitApplicationRequest", targetNamespace = "http://api.vetrf.ru/schema/cdm/application/ws-definitions", className = "ru.vetrf.api.schema.cdm.application.ws_definitions.SubmitApplicationRequest")
    @ResponseWrapper(localName = "submitApplicationResponse", targetNamespace = "http://api.vetrf.ru/schema/cdm/application/ws-definitions", className = "ru.vetrf.api.schema.cdm.application.ws_definitions.SubmitApplicationResponse")
    public void submitApplicationRequest(
        @WebParam(name = "apiKey", targetNamespace = "http://api.vetrf.ru/schema/cdm/application/ws-definitions")
        String apiKey,
        @WebParam(name = "application", targetNamespace = "http://api.vetrf.ru/schema/cdm/application", mode = WebParam.Mode.INOUT)
        Holder<Application> application)
        throws AccessDeniedFault, IncorrectRequestFault, InternalServiceFault, UnknownServiceIdFault, UnsupportedApplicationDataTypeFault
    ;

    /**
     * 
     * @param request
     * @return
     *     returns ru.vetrf.api.schema.cdm.application.ws_definitions.ReceiveApplicationResultResponse
     * @throws AccessDeniedFault
     * @throws IncorrectRequestFault
     * @throws ApplicationNotFoundFault
     * @throws InternalServiceFault
     */
    @WebMethod(action = "receiveApplicationResult")
    @WebResult(name = "receiveApplicationResultResponse", targetNamespace = "http://api.vetrf.ru/schema/cdm/application/ws-definitions", partName = "response")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public ReceiveApplicationResultResponse receiveApplicationResult(
        @WebParam(name = "receiveApplicationResultRequest", targetNamespace = "http://api.vetrf.ru/schema/cdm/application/ws-definitions", partName = "request")
        ReceiveApplicationResultRequest request)
        throws AccessDeniedFault, ApplicationNotFoundFault, IncorrectRequestFault, InternalServiceFault
    ;

}
