
package ru.vetrf.api.schema.cdm.registry.product.service.v2;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ProductServiceBindingQSService", targetNamespace = "http://api.vetrf.ru/schema/cdm/registry/product/service/v2", wsdlLocation = "http://api.vetrf.ru/schema/platform/services/2.1-RC-last/ProductService_v2.1_production.wsdl")
public class ProductServiceBindingQSService
    extends Service
{

    private final static URL PRODUCTSERVICEBINDINGQSSERVICE_WSDL_LOCATION;
    private final static WebServiceException PRODUCTSERVICEBINDINGQSSERVICE_EXCEPTION;
    private final static QName PRODUCTSERVICEBINDINGQSSERVICE_QNAME = new QName("http://api.vetrf.ru/schema/cdm/registry/product/service/v2", "ProductServiceBindingQSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://api.vetrf.ru/schema/platform/services/2.1-RC-last/ProductService_v2.1_production.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PRODUCTSERVICEBINDINGQSSERVICE_WSDL_LOCATION = url;
        PRODUCTSERVICEBINDINGQSSERVICE_EXCEPTION = e;
    }

    public ProductServiceBindingQSService() {
        super(__getWsdlLocation(), PRODUCTSERVICEBINDINGQSSERVICE_QNAME);
    }

    public ProductServiceBindingQSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PRODUCTSERVICEBINDINGQSSERVICE_QNAME, features);
    }

    public ProductServiceBindingQSService(URL wsdlLocation) {
        super(wsdlLocation, PRODUCTSERVICEBINDINGQSSERVICE_QNAME);
    }

    public ProductServiceBindingQSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PRODUCTSERVICEBINDINGQSSERVICE_QNAME, features);
    }

    public ProductServiceBindingQSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProductServiceBindingQSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ProductServicePortType
     */
    @WebEndpoint(name = "ProductServiceBindingQSPort")
    public ProductServicePortType getProductServiceBindingQSPort() {
        return super.getPort(new QName("http://api.vetrf.ru/schema/cdm/registry/product/service/v2", "ProductServiceBindingQSPort"), ProductServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProductServicePortType
     */
    @WebEndpoint(name = "ProductServiceBindingQSPort")
    public ProductServicePortType getProductServiceBindingQSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://api.vetrf.ru/schema/cdm/registry/product/service/v2", "ProductServiceBindingQSPort"), ProductServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PRODUCTSERVICEBINDINGQSSERVICE_EXCEPTION!= null) {
            throw PRODUCTSERVICEBINDINGQSSERVICE_EXCEPTION;
        }
        return PRODUCTSERVICEBINDINGQSSERVICE_WSDL_LOCATION;
    }

}
