
package ru.vetrf.api.schema.cdm.registry.ikar.service.v2;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import ru.vetrf.api.schema.cdm.registry.ws_definitions.v2.FindLocalityListByNameRequest;
import ru.vetrf.api.schema.cdm.registry.ws_definitions.v2.FindLocalityListByNameResponse;
import ru.vetrf.api.schema.cdm.registry.ws_definitions.v2.FindStreetListByNameRequest;
import ru.vetrf.api.schema.cdm.registry.ws_definitions.v2.FindStreetListByNameResponse;
import ru.vetrf.api.schema.cdm.registry.ws_definitions.v2.GetAllCountryListRequest;
import ru.vetrf.api.schema.cdm.registry.ws_definitions.v2.GetAllCountryListResponse;
import ru.vetrf.api.schema.cdm.registry.ws_definitions.v2.GetCountryByGuidRequest;
import ru.vetrf.api.schema.cdm.registry.ws_definitions.v2.GetCountryByGuidResponse;
import ru.vetrf.api.schema.cdm.registry.ws_definitions.v2.GetCountryByUuidRequest;
import ru.vetrf.api.schema.cdm.registry.ws_definitions.v2.GetCountryByUuidResponse;
import ru.vetrf.api.schema.cdm.registry.ws_definitions.v2.GetCountryChangesListRequest;
import ru.vetrf.api.schema.cdm.registry.ws_definitions.v2.GetCountryChangesListResponse;
import ru.vetrf.api.schema.cdm.registry.ws_definitions.v2.GetDistrictByGuidRequest;
import ru.vetrf.api.schema.cdm.registry.ws_definitions.v2.GetDistrictByGuidResponse;
import ru.vetrf.api.schema.cdm.registry.ws_definitions.v2.GetDistrictByUuidRequest;
import ru.vetrf.api.schema.cdm.registry.ws_definitions.v2.GetDistrictByUuidResponse;
import ru.vetrf.api.schema.cdm.registry.ws_definitions.v2.GetDistrictChangesListRequest;
import ru.vetrf.api.schema.cdm.registry.ws_definitions.v2.GetDistrictChangesListResponse;
import ru.vetrf.api.schema.cdm.registry.ws_definitions.v2.GetDistrictListByRegionRequest;
import ru.vetrf.api.schema.cdm.registry.ws_definitions.v2.GetDistrictListByRegionResponse;
import ru.vetrf.api.schema.cdm.registry.ws_definitions.v2.GetLocalityChangesListRequest;
import ru.vetrf.api.schema.cdm.registry.ws_definitions.v2.GetLocalityChangesListResponse;
import ru.vetrf.api.schema.cdm.registry.ws_definitions.v2.GetLocalityListByDistrictRequest;
import ru.vetrf.api.schema.cdm.registry.ws_definitions.v2.GetLocalityListByDistrictResponse;
import ru.vetrf.api.schema.cdm.registry.ws_definitions.v2.GetLocalityListByLocalityRequest;
import ru.vetrf.api.schema.cdm.registry.ws_definitions.v2.GetLocalityListByLocalityResponse;
import ru.vetrf.api.schema.cdm.registry.ws_definitions.v2.GetLocalityListByRegionRequest;
import ru.vetrf.api.schema.cdm.registry.ws_definitions.v2.GetLocalityListByRegionResponse;
import ru.vetrf.api.schema.cdm.registry.ws_definitions.v2.GetRegionByGuidRequest;
import ru.vetrf.api.schema.cdm.registry.ws_definitions.v2.GetRegionByGuidResponse;
import ru.vetrf.api.schema.cdm.registry.ws_definitions.v2.GetRegionByUuidRequest;
import ru.vetrf.api.schema.cdm.registry.ws_definitions.v2.GetRegionByUuidResponse;
import ru.vetrf.api.schema.cdm.registry.ws_definitions.v2.GetRegionChangesListRequest;
import ru.vetrf.api.schema.cdm.registry.ws_definitions.v2.GetRegionChangesListResponse;
import ru.vetrf.api.schema.cdm.registry.ws_definitions.v2.GetRegionListByCountryRequest;
import ru.vetrf.api.schema.cdm.registry.ws_definitions.v2.GetRegionListByCountryResponse;
import ru.vetrf.api.schema.cdm.registry.ws_definitions.v2.GetStreetChangesListRequest;
import ru.vetrf.api.schema.cdm.registry.ws_definitions.v2.GetStreetChangesListResponse;
import ru.vetrf.api.schema.cdm.registry.ws_definitions.v2.GetStreetListByLocalityRequest;
import ru.vetrf.api.schema.cdm.registry.ws_definitions.v2.GetStreetListByLocalityResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IkarServicePortType", targetNamespace = "http://api.vetrf.ru/schema/cdm/registry/ikar/service/v2")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ru.vetrf.api.schema.cdm.dictionary.v2.ObjectFactory.class,
    ru.vetrf.api.schema.cdm.base.ObjectFactory.class,
    ru.vetrf.api.schema.cdm.base.ws_definitions.ObjectFactory.class,
    ru.vetrf.api.schema.cdm.registry.ws_definitions.v2.ObjectFactory.class
})
public interface IkarServicePortType {


    /**
     * Получение списка записей стран с активным
     *                 статусом.
     *                 Выполнение операции заканчивается либо возвратом списка стран,
     *                 либо ошибкой, в случае если параметры запроса не корректны или произошла
     *                 иная ошибка выполнения запроса.
     *             
     * 
     * @param request
     * @return
     *     returns ru.vetrf.api.schema.cdm.registry.ws_definitions.v2.GetAllCountryListResponse
     * @throws IncorrectRequestFault
     * @throws OffsetOutOfRangeFault
     * @throws InternalServiceFault
     */
    @WebMethod(operationName = "GetAllCountryList", action = "GetAllCountryList")
    @WebResult(name = "getAllCountryListResponse", targetNamespace = "http://api.vetrf.ru/schema/cdm/registry/ws-definitions/v2", partName = "response")
    public GetAllCountryListResponse getAllCountryList(
        @WebParam(name = "getAllCountryListRequest", targetNamespace = "http://api.vetrf.ru/schema/cdm/registry/ws-definitions/v2", partName = "request")
        GetAllCountryListRequest request)
        throws IncorrectRequestFault, InternalServiceFault, OffsetOutOfRangeFault
    ;

    /**
     * Получение последней записи страны по
     *                 глобальному идентификатору.
     *                 Выполнение операции заканчивается либо возвратом объекта страны,
     *                 либо ошибкой, в случае если параметры запроса не корректны, если запись
     *                 по запросу не найдена
     *                 или произошла иная ошибка выполнения запроса.
     *             
     * 
     * @param request
     * @return
     *     returns ru.vetrf.api.schema.cdm.registry.ws_definitions.v2.GetCountryByGuidResponse
     * @throws IncorrectRequestFault
     * @throws EntityNotFoundFault
     * @throws InternalServiceFault
     */
    @WebMethod(operationName = "GetCountryByGuid", action = "GetCountryByGuid")
    @WebResult(name = "getCountryByGuidResponse", targetNamespace = "http://api.vetrf.ru/schema/cdm/registry/ws-definitions/v2", partName = "response")
    public GetCountryByGuidResponse getCountryByGuid(
        @WebParam(name = "getCountryByGuidRequest", targetNamespace = "http://api.vetrf.ru/schema/cdm/registry/ws-definitions/v2", partName = "request")
        GetCountryByGuidRequest request)
        throws EntityNotFoundFault, IncorrectRequestFault, InternalServiceFault
    ;

    /**
     * Получение записи страны по идентификатору.
     *                 Выполнение операции заканчивается либо возвратом объекта страны,
     *                 либо ошибкой, в случае если параметры запроса не корректны, если запись
     *                 по запросу не найдена
     *                 или произошла иная ошибка выполнения запроса.
     *             
     * 
     * @param request
     * @return
     *     returns ru.vetrf.api.schema.cdm.registry.ws_definitions.v2.GetCountryByUuidResponse
     * @throws IncorrectRequestFault
     * @throws EntityNotFoundFault
     * @throws InternalServiceFault
     */
    @WebMethod(operationName = "GetCountryByUuid", action = "GetCountryByUuid")
    @WebResult(name = "getCountryByUuidResponse", targetNamespace = "http://api.vetrf.ru/schema/cdm/registry/ws-definitions/v2", partName = "response")
    public GetCountryByUuidResponse getCountryByUuid(
        @WebParam(name = "getCountryByUuidRequest", targetNamespace = "http://api.vetrf.ru/schema/cdm/registry/ws-definitions/v2", partName = "request")
        GetCountryByUuidRequest request)
        throws EntityNotFoundFault, IncorrectRequestFault, InternalServiceFault
    ;

    /**
     * Получение истории изменений в списке стран.
     *                 Выполнение операции заканчивается либо возвратом списка стран,
     *                 либо ошибкой, в случае если параметры запроса не корректны или произошла
     *                 иная ошибка выполнения запроса.
     *             
     * 
     * @param request
     * @return
     *     returns ru.vetrf.api.schema.cdm.registry.ws_definitions.v2.GetCountryChangesListResponse
     * @throws IncorrectRequestFault
     * @throws OffsetOutOfRangeFault
     * @throws InternalServiceFault
     */
    @WebMethod(operationName = "GetCountryChangesList", action = "GetCountryChangesList")
    @WebResult(name = "getCountryChangesListResponse", targetNamespace = "http://api.vetrf.ru/schema/cdm/registry/ws-definitions/v2", partName = "response")
    public GetCountryChangesListResponse getCountryChangesList(
        @WebParam(name = "getCountryChangesListRequest", targetNamespace = "http://api.vetrf.ru/schema/cdm/registry/ws-definitions/v2", partName = "request")
        GetCountryChangesListRequest request)
        throws IncorrectRequestFault, InternalServiceFault, OffsetOutOfRangeFault
    ;

    /**
     * Получение списка записей регионов с активным
     *                 статусом по стране.
     *                 Выполнение операции заканчивается либо возвратом списка регионов,
     *                 либо ошибкой, в случае если параметры запроса не корректны или произошла
     *                 иная ошибка выполнения запроса.
     *             
     * 
     * @param request
     * @return
     *     returns ru.vetrf.api.schema.cdm.registry.ws_definitions.v2.GetRegionListByCountryResponse
     * @throws IncorrectRequestFault
     * @throws EntityNotFoundFault
     * @throws OffsetOutOfRangeFault
     * @throws InternalServiceFault
     */
    @WebMethod(operationName = "GetRegionListByCountry", action = "GetRegionListByCountry")
    @WebResult(name = "getRegionListByCountryResponse", targetNamespace = "http://api.vetrf.ru/schema/cdm/registry/ws-definitions/v2", partName = "response")
    public GetRegionListByCountryResponse getRegionListByCountry(
        @WebParam(name = "getRegionListByCountryRequest", targetNamespace = "http://api.vetrf.ru/schema/cdm/registry/ws-definitions/v2", partName = "request")
        GetRegionListByCountryRequest request)
        throws EntityNotFoundFault, IncorrectRequestFault, InternalServiceFault, OffsetOutOfRangeFault
    ;

    /**
     * Получение последней записи региона по
     *                 глобальному идентификатору.
     *                 Выполнение операции заканчивается либо возвратом объекта региона,
     *                 либо ошибкой, в случае если параметры запроса не корректны, если запись
     *                 по запросу не найдена
     *                 или произошла иная ошибка выполнения запроса.
     *             
     * 
     * @param request
     * @return
     *     returns ru.vetrf.api.schema.cdm.registry.ws_definitions.v2.GetRegionByGuidResponse
     * @throws IncorrectRequestFault
     * @throws EntityNotFoundFault
     * @throws InternalServiceFault
     */
    @WebMethod(operationName = "GetRegionByGuid", action = "GetRegionByGuid")
    @WebResult(name = "getRegionByGuidResponse", targetNamespace = "http://api.vetrf.ru/schema/cdm/registry/ws-definitions/v2", partName = "response")
    public GetRegionByGuidResponse getRegionByGuid(
        @WebParam(name = "getRegionByGuidRequest", targetNamespace = "http://api.vetrf.ru/schema/cdm/registry/ws-definitions/v2", partName = "request")
        GetRegionByGuidRequest request)
        throws EntityNotFoundFault, IncorrectRequestFault, InternalServiceFault
    ;

    /**
     * Получение записи региона по идентификатору.
     *                 Выполнение операции заканчивается либо возвратом объекта региона,
     *                 либо ошибкой, в случае если параметры запроса не корректны, если запись
     *                 по запросу не найдена
     *                 или произошла иная ошибка выполнения запроса.
     *             
     * 
     * @param request
     * @return
     *     returns ru.vetrf.api.schema.cdm.registry.ws_definitions.v2.GetRegionByUuidResponse
     * @throws IncorrectRequestFault
     * @throws EntityNotFoundFault
     * @throws InternalServiceFault
     */
    @WebMethod(operationName = "GetRegionByUuid", action = "GetRegionByUuid")
    @WebResult(name = "getRegionByUuidResponse", targetNamespace = "http://api.vetrf.ru/schema/cdm/registry/ws-definitions/v2", partName = "response")
    public GetRegionByUuidResponse getRegionByUuid(
        @WebParam(name = "getRegionByUuidRequest", targetNamespace = "http://api.vetrf.ru/schema/cdm/registry/ws-definitions/v2", partName = "request")
        GetRegionByUuidRequest request)
        throws EntityNotFoundFault, IncorrectRequestFault, InternalServiceFault
    ;

    /**
     * Получение истории изменений в списке регионов.
     *                 Выполнение операции заканчивается либо возвратом списка регионов,
     *                 либо ошибкой, в случае если параметры запроса не корректны или
     *                 произошла иная ошибка выполнения запроса.
     *             
     * 
     * @param request
     * @return
     *     returns ru.vetrf.api.schema.cdm.registry.ws_definitions.v2.GetRegionChangesListResponse
     * @throws IncorrectRequestFault
     * @throws OffsetOutOfRangeFault
     * @throws InternalServiceFault
     */
    @WebMethod(operationName = "GetRegionChangesList", action = "GetRegionChangesList")
    @WebResult(name = "getRegionChangesListResponse", targetNamespace = "http://api.vetrf.ru/schema/cdm/registry/ws-definitions/v2", partName = "response")
    public GetRegionChangesListResponse getRegionChangesList(
        @WebParam(name = "getRegionChangesListRequest", targetNamespace = "http://api.vetrf.ru/schema/cdm/registry/ws-definitions/v2", partName = "request")
        GetRegionChangesListRequest request)
        throws IncorrectRequestFault, InternalServiceFault, OffsetOutOfRangeFault
    ;

    /**
     * Получение списка записей районов с активным
     *                 статусом по региону.
     *                 Выполнение операции заканчивается либо возвратом списка районов,
     *                 либо ошибкой, в случае если параметры запроса не корректны или произошла
     *                 иная ошибка выполнения запроса.
     *             
     * 
     * @param request
     * @return
     *     returns ru.vetrf.api.schema.cdm.registry.ws_definitions.v2.GetDistrictListByRegionResponse
     * @throws IncorrectRequestFault
     * @throws EntityNotFoundFault
     * @throws OffsetOutOfRangeFault
     * @throws InternalServiceFault
     */
    @WebMethod(operationName = "GetDistrictListByRegion", action = "GetDistrictListByRegion")
    @WebResult(name = "getDistrictListByRegionResponse", targetNamespace = "http://api.vetrf.ru/schema/cdm/registry/ws-definitions/v2", partName = "response")
    public GetDistrictListByRegionResponse getDistrictListByRegion(
        @WebParam(name = "getDistrictListByRegionRequest", targetNamespace = "http://api.vetrf.ru/schema/cdm/registry/ws-definitions/v2", partName = "request")
        GetDistrictListByRegionRequest request)
        throws EntityNotFoundFault, IncorrectRequestFault, InternalServiceFault, OffsetOutOfRangeFault
    ;

    /**
     * Получение последней записи района по
     *                 глобальному идентификатору.
     *                 Выполнение операции заканчивается либо возвратом объекта района,
     *                 либо ошибкой, в случае если параметры запроса не корректны, если запись
     *                 по запросу не найдена
     *                 или произошла иная ошибка выполнения запроса.
     *             
     * 
     * @param request
     * @return
     *     returns ru.vetrf.api.schema.cdm.registry.ws_definitions.v2.GetDistrictByGuidResponse
     * @throws IncorrectRequestFault
     * @throws EntityNotFoundFault
     * @throws InternalServiceFault
     */
    @WebMethod(operationName = "GetDistrictByGuid", action = "GetDistrictByGuid")
    @WebResult(name = "getDistrictByGuidResponse", targetNamespace = "http://api.vetrf.ru/schema/cdm/registry/ws-definitions/v2", partName = "response")
    public GetDistrictByGuidResponse getDistrictByGuid(
        @WebParam(name = "getDistrictByGuidRequest", targetNamespace = "http://api.vetrf.ru/schema/cdm/registry/ws-definitions/v2", partName = "request")
        GetDistrictByGuidRequest request)
        throws EntityNotFoundFault, IncorrectRequestFault, InternalServiceFault
    ;

    /**
     * Получение последней записи района по
     *                 идентификатору.
     *                 Выполнение операции заканчивается либо возвратом объекта района,
     *                 либо ошибкой, в случае если параметры запроса не корректны, если запись
     *                 по запросу не найдена
     *                 или произошла иная ошибка выполнения запроса.
     *             
     * 
     * @param request
     * @return
     *     returns ru.vetrf.api.schema.cdm.registry.ws_definitions.v2.GetDistrictByUuidResponse
     * @throws IncorrectRequestFault
     * @throws EntityNotFoundFault
     * @throws InternalServiceFault
     */
    @WebMethod(operationName = "GetDistrictByUuid", action = "GetDistrictByUuid")
    @WebResult(name = "getDistrictByUuidResponse", targetNamespace = "http://api.vetrf.ru/schema/cdm/registry/ws-definitions/v2", partName = "response")
    public GetDistrictByUuidResponse getDistrictByUuid(
        @WebParam(name = "getDistrictByUuidRequest", targetNamespace = "http://api.vetrf.ru/schema/cdm/registry/ws-definitions/v2", partName = "request")
        GetDistrictByUuidRequest request)
        throws EntityNotFoundFault, IncorrectRequestFault, InternalServiceFault
    ;

    /**
     * Получение истории изменений в списке районов.
     *                 Выполнение операции заканчивается либо возвратом списка районов,
     *                 либо ошибкой, в случае если параметры запроса не корректны или
     *                 произошла иная ошибка выполнения запроса.
     *             
     * 
     * @param request
     * @return
     *     returns ru.vetrf.api.schema.cdm.registry.ws_definitions.v2.GetDistrictChangesListResponse
     * @throws IncorrectRequestFault
     * @throws OffsetOutOfRangeFault
     * @throws InternalServiceFault
     */
    @WebMethod(operationName = "GetDistrictChangesList", action = "GetDistrictChangesList")
    @WebResult(name = "getDistrictChangesListResponse", targetNamespace = "http://api.vetrf.ru/schema/cdm/registry/ws-definitions/v2", partName = "response")
    public GetDistrictChangesListResponse getDistrictChangesList(
        @WebParam(name = "getDistrictChangesListRequest", targetNamespace = "http://api.vetrf.ru/schema/cdm/registry/ws-definitions/v2", partName = "request")
        GetDistrictChangesListRequest request)
        throws IncorrectRequestFault, InternalServiceFault, OffsetOutOfRangeFault
    ;

    /**
     * Получение списка записей населенных пунктов с активным
     *                 статусом по региону.
     *                 Выполнение операции заканчивается либо возвратом списка населенных пунктов,
     *                 либо ошибкой, в случае если параметры запроса не корректны или произошла
     *                 иная ошибка выполнения запроса.
     *             
     * 
     * @param request
     * @return
     *     returns ru.vetrf.api.schema.cdm.registry.ws_definitions.v2.GetLocalityListByRegionResponse
     * @throws IncorrectRequestFault
     * @throws EntityNotFoundFault
     * @throws OffsetOutOfRangeFault
     * @throws InternalServiceFault
     */
    @WebMethod(operationName = "GetLocalityListByRegion", action = "GetLocalityListByRegion")
    @WebResult(name = "getLocalityListByRegionResponse", targetNamespace = "http://api.vetrf.ru/schema/cdm/registry/ws-definitions/v2", partName = "response")
    public GetLocalityListByRegionResponse getLocalityListByRegion(
        @WebParam(name = "getLocalityListByRegionRequest", targetNamespace = "http://api.vetrf.ru/schema/cdm/registry/ws-definitions/v2", partName = "request")
        GetLocalityListByRegionRequest request)
        throws EntityNotFoundFault, IncorrectRequestFault, InternalServiceFault, OffsetOutOfRangeFault
    ;

    /**
     * Получение списка записей населенных пунктов с активным
     *                 статусом по району.
     *                 Выполнение операции заканчивается либо возвратом списка населенных пунктов,
     *                 либо ошибкой, в случае если параметры запроса не корректны или произошла
     *                 иная ошибка выполнения запроса.
     *             
     * 
     * @param request
     * @return
     *     returns ru.vetrf.api.schema.cdm.registry.ws_definitions.v2.GetLocalityListByDistrictResponse
     * @throws IncorrectRequestFault
     * @throws EntityNotFoundFault
     * @throws OffsetOutOfRangeFault
     * @throws InternalServiceFault
     */
    @WebMethod(operationName = "GetLocalityListByDistrict", action = "GetLocalityListByDistrict")
    @WebResult(name = "getLocalityListByDistrictResponse", targetNamespace = "http://api.vetrf.ru/schema/cdm/registry/ws-definitions/v2", partName = "response")
    public GetLocalityListByDistrictResponse getLocalityListByDistrict(
        @WebParam(name = "getLocalityListByDistrictRequest", targetNamespace = "http://api.vetrf.ru/schema/cdm/registry/ws-definitions/v2", partName = "request")
        GetLocalityListByDistrictRequest request)
        throws EntityNotFoundFault, IncorrectRequestFault, InternalServiceFault, OffsetOutOfRangeFault
    ;

    /**
     * Получение списка зависимых записей населенных пунктов с активным
     *                 статусом по населенному пункту.
     *                 Выполнение операции заканчивается либо возвратом списка населенных пунктов,
     *                 либо ошибкой, в случае если параметры запроса не корректны или произошла
     *                 иная ошибка выполнения запроса.
     *             
     * 
     * @param request
     * @return
     *     returns ru.vetrf.api.schema.cdm.registry.ws_definitions.v2.GetLocalityListByLocalityResponse
     * @throws IncorrectRequestFault
     * @throws EntityNotFoundFault
     * @throws OffsetOutOfRangeFault
     * @throws InternalServiceFault
     */
    @WebMethod(operationName = "GetLocalityListByLocality", action = "GetLocalityListByLocality")
    @WebResult(name = "getLocalityListByLocalityResponse", targetNamespace = "http://api.vetrf.ru/schema/cdm/registry/ws-definitions/v2", partName = "response")
    public GetLocalityListByLocalityResponse getLocalityListByLocality(
        @WebParam(name = "getLocalityListByLocalityRequest", targetNamespace = "http://api.vetrf.ru/schema/cdm/registry/ws-definitions/v2", partName = "request")
        GetLocalityListByLocalityRequest request)
        throws EntityNotFoundFault, IncorrectRequestFault, InternalServiceFault, OffsetOutOfRangeFault
    ;

    /**
     * Получение списка записей улиц с активным
     *                 статусом по региону.
     *                 Выполнение операции заканчивается либо возвратом списка улиц,
     *                 либо ошибкой, в случае если параметры запроса не корректны или произошла
     *                 иная ошибка выполнения запроса.
     *             
     * 
     * @param request
     * @return
     *     returns ru.vetrf.api.schema.cdm.registry.ws_definitions.v2.GetStreetListByLocalityResponse
     * @throws IncorrectRequestFault
     * @throws EntityNotFoundFault
     * @throws OffsetOutOfRangeFault
     * @throws InternalServiceFault
     */
    @WebMethod(operationName = "GetStreetListByLocality", action = "GetStreetListByLocality")
    @WebResult(name = "getStreetListByLocalityResponse", targetNamespace = "http://api.vetrf.ru/schema/cdm/registry/ws-definitions/v2", partName = "response")
    public GetStreetListByLocalityResponse getStreetListByLocality(
        @WebParam(name = "getStreetListByLocalityRequest", targetNamespace = "http://api.vetrf.ru/schema/cdm/registry/ws-definitions/v2", partName = "request")
        GetStreetListByLocalityRequest request)
        throws EntityNotFoundFault, IncorrectRequestFault, InternalServiceFault, OffsetOutOfRangeFault
    ;

    /**
     * Получение списка записей населенных пунктов с активным
     *                 статусом по шаблону и региону.
     *                 Выполнение операции заканчивается либо возвратом списка населенных пунктов,
     *                 либо ошибкой, в случае если параметры запроса не корректны или произошла
     *                 иная ошибка выполнения запроса.
     *             
     * 
     * @param request
     * @return
     *     returns ru.vetrf.api.schema.cdm.registry.ws_definitions.v2.FindLocalityListByNameResponse
     * @throws IncorrectRequestFault
     * @throws EntityNotFoundFault
     * @throws OffsetOutOfRangeFault
     * @throws InternalServiceFault
     */
    @WebMethod(operationName = "FindLocalityListByName", action = "FindLocalityListByName")
    @WebResult(name = "findLocalityListByNameResponse", targetNamespace = "http://api.vetrf.ru/schema/cdm/registry/ws-definitions/v2", partName = "response")
    public FindLocalityListByNameResponse findLocalityListByName(
        @WebParam(name = "findLocalityListByNameRequest", targetNamespace = "http://api.vetrf.ru/schema/cdm/registry/ws-definitions/v2", partName = "request")
        FindLocalityListByNameRequest request)
        throws EntityNotFoundFault, IncorrectRequestFault, InternalServiceFault, OffsetOutOfRangeFault
    ;

    /**
     * Получение списка записей улиц с активным
     *                 статусом по шаблону и населенному пункту.
     *                 Выполнение операции заканчивается либо возвратом списка улиц,
     *                 либо ошибкой, в случае если параметры запроса не корректны или произошла
     *                 иная ошибка выполнения запроса.
     *             
     * 
     * @param request
     * @return
     *     returns ru.vetrf.api.schema.cdm.registry.ws_definitions.v2.FindStreetListByNameResponse
     * @throws IncorrectRequestFault
     * @throws EntityNotFoundFault
     * @throws OffsetOutOfRangeFault
     * @throws InternalServiceFault
     */
    @WebMethod(operationName = "FindStreetListByName", action = "FindStreetListByName")
    @WebResult(name = "findStreetListByNameResponse", targetNamespace = "http://api.vetrf.ru/schema/cdm/registry/ws-definitions/v2", partName = "response")
    public FindStreetListByNameResponse findStreetListByName(
        @WebParam(name = "findStreetListByNameRequest", targetNamespace = "http://api.vetrf.ru/schema/cdm/registry/ws-definitions/v2", partName = "request")
        FindStreetListByNameRequest request)
        throws EntityNotFoundFault, IncorrectRequestFault, InternalServiceFault, OffsetOutOfRangeFault
    ;

    /**
     * Получение истории изменений в списке населенных пунктов.
     *                 Выполнение операции заканчивается либо возвратом списка населенных пунктов,
     *                 либо ошибкой, в случае если параметры запроса не корректны или
     *                 произошла иная ошибка выполнения запроса.
     *             
     * 
     * @param request
     * @return
     *     returns ru.vetrf.api.schema.cdm.registry.ws_definitions.v2.GetLocalityChangesListResponse
     * @throws IncorrectRequestFault
     * @throws OffsetOutOfRangeFault
     * @throws InternalServiceFault
     */
    @WebMethod(operationName = "GetLocalityChangesList", action = "GetLocalityChangesList")
    @WebResult(name = "getLocalityChangesListResponse", targetNamespace = "http://api.vetrf.ru/schema/cdm/registry/ws-definitions/v2", partName = "response")
    public GetLocalityChangesListResponse getLocalityChangesList(
        @WebParam(name = "getLocalityChangesListRequest", targetNamespace = "http://api.vetrf.ru/schema/cdm/registry/ws-definitions/v2", partName = "request")
        GetLocalityChangesListRequest request)
        throws IncorrectRequestFault, InternalServiceFault, OffsetOutOfRangeFault
    ;

    /**
     * Получение истории изменений в списке улиц.
     *                 Выполнение операции заканчивается либо возвратом списка улиц,
     *                 либо ошибкой, в случае если параметры запроса не корректны или
     *                 произошла иная ошибка выполнения запроса.
     *             
     * 
     * @param request
     * @return
     *     returns ru.vetrf.api.schema.cdm.registry.ws_definitions.v2.GetStreetChangesListResponse
     * @throws IncorrectRequestFault
     * @throws OffsetOutOfRangeFault
     * @throws InternalServiceFault
     */
    @WebMethod(operationName = "GetStreetChangesList", action = "GetStreetChangesList")
    @WebResult(name = "getStreetChangesListResponse", targetNamespace = "http://api.vetrf.ru/schema/cdm/registry/ws-definitions/v2", partName = "response")
    public GetStreetChangesListResponse getStreetChangesList(
        @WebParam(name = "getStreetChangesListRequest", targetNamespace = "http://api.vetrf.ru/schema/cdm/registry/ws-definitions/v2", partName = "request")
        GetStreetChangesListRequest request)
        throws IncorrectRequestFault, InternalServiceFault, OffsetOutOfRangeFault
    ;

}
